//! DocumenterCoordinatorStrategy — Phase 1: strategy planning.
//!
//! Single-turn structured JSON output. The LLM analyzes the task and
//! produces a `StrategyOutput` with one plan per requested document.
//! No tools, no streaming.

use async_trait::async_trait;
use serde_json::Value;
use uuid::Uuid;

use crate::llm::{Message, Tool};
use crate::server::hub::error::HubError;
use crate::server::hub::strategy::ExecutionStrategy;
use crate::server::state::AppState;
use crate::types::UserId;

/// Configuration for the documenter coordinator phase.
pub struct DocumenterCoordinatorConfig {
    /// System prompt — auto-generated by `compilers::documenter::prompt::documenter_prompt()`.
    pub system_prompt: String,
    /// Model to use (from workflow config or default).
    pub model_id: String,
    /// Optional state for token ledger writes.
    pub state: Option<AppState>,
    /// Optional user ID for token ledger attribution.
    pub user_id: Option<UserId>,
}

/// Phase 1 strategy: analyze task and produce research/writing plans.
pub struct DocumenterCoordinatorStrategy {
    config: DocumenterCoordinatorConfig,
}

impl DocumenterCoordinatorStrategy {
    pub fn new(config: DocumenterCoordinatorConfig) -> Self {
        Self { config }
    }
}

#[async_trait]
impl ExecutionStrategy for DocumenterCoordinatorStrategy {
    fn system_prompt(&self) -> &str {
        &self.config.system_prompt
    }

    fn tools(&self) -> Vec<Tool> {
        vec![]
    }

    fn model_id(&self) -> &str {
        &self.config.model_id
    }

    fn max_rounds(&self) -> u32 {
        1
    }

    fn context_budget(&self) -> usize {
        100_000
    }

    fn streaming(&self) -> bool {
        false
    }

    fn temperature(&self) -> f32 {
        0.3
    }

    async fn build_messages(&self, input: &str) -> Result<Vec<Message>, HubError> {
        Ok(vec![Message::user(input)])
    }

    fn state(&self) -> Option<&AppState> {
        self.config.state.as_ref()
    }

    fn user_id(&self) -> Option<Uuid> {
        self.config.user_id.map(|u| u.0)
    }

    async fn execute_tool(&self, _name: &str, _input: &Value) -> Value {
        serde_json::json!({"error": "documenter coordinator does not execute tools"})
    }
}
