//! Built-in protocol definitions seeded at startup.
//!
//! These are framework-level protocol types that exist system-wide.
//! Uses deterministic UUIDs so re-seeding is idempotent.
//!
//! Protocol agents are NOT stored as separate DB records — the expanders
//! handle all protocol logic dynamically at expansion time. Schemas and
//! prompts are generated by `schema_gen` and `prompt_gen` based on port
//! configuration. The protocol row stores only the type metadata and
//! default config.

use uuid::Uuid;

/// A built-in protocol definition for seeding.
pub struct BuiltinProtocol {
    pub id: Uuid,
    pub name: String,
    pub description: String,
    pub protocol_type: String,
    pub config: serde_json::Value,
}

/// Namespace UUID for deterministic protocol ID generation.
const PROTOCOLS_NS: Uuid = Uuid::from_bytes([
    0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2d, 0x6e, 0x65, 0x78, 0x6f, 0x72, 0x21,
]);

/// Returns the 5 built-in protocol definitions.
///
/// Each protocol type has a corresponding expander in `hub::protocols::expanders`
/// that generates schemas, prompts, steps, and edges dynamically based on port
/// configuration at expansion time.
pub fn builtin_protocol_definitions() -> Vec<BuiltinProtocol> {
    vec![
        // =====================================================================
        // 1. Decomposition — fan out to specialist agents
        // =====================================================================
        BuiltinProtocol {
            id: Uuid::new_v5(&PROTOCOLS_NS, b"Decomposition"),
            name: "Decomposition".into(),
            description: "Decompose a task into subtasks and fan out to specialist agents. \
                Configure ports to define which agents receive subtasks. The orchestrator \
                analyzes the input and assigns work to each port's agent based on expertise."
                .into(),
            protocol_type: "decomp".into(),
            config: serde_json::json!({}),
        },
        // =====================================================================
        // 2. Route — route to best-fit specialist
        // =====================================================================
        BuiltinProtocol {
            id: Uuid::new_v5(&PROTOCOLS_NS, b"Route"),
            name: "Route".into(),
            description: "Analyze input and route to exactly one specialist agent. \
                Configure ports to define routing targets. The orchestrator evaluates \
                the input and selects the single best-fit agent based on the request's \
                intent and each agent's capabilities."
                .into(),
            protocol_type: "route".into(),
            config: serde_json::json!({}),
        },
        // =====================================================================
        // 3. Review — structured decision with feedback
        // =====================================================================
        BuiltinProtocol {
            id: Uuid::new_v5(&PROTOCOLS_NS, b"Review"),
            name: "Review".into(),
            description: "Evaluate input against quality criteria and produce a structured \
                decision with feedback. Configure decisions in the config to define the \
                available outcomes (e.g. approve, reject, revise). Downstream routing \
                can be conditioned on the decision."
                .into(),
            protocol_type: "review".into(),
            config: serde_json::json!({
                "decisions": ["approve", "reject", "revise"]
            }),
        },
        // =====================================================================
        // 4. Transform — process input to structured output
        // =====================================================================
        BuiltinProtocol {
            id: Uuid::new_v5(&PROTOCOLS_NS, b"Transform"),
            name: "Transform".into(),
            description: "Process input and produce structured output matching a schema. \
                The agent transforms the input data into the format defined by the \
                output schema. Useful for data extraction, reformatting, and \
                normalization steps."
                .into(),
            protocol_type: "transform".into(),
            config: serde_json::json!({}),
        },
        // =====================================================================
        // 5. Default — standard structured output
        // =====================================================================
        BuiltinProtocol {
            id: Uuid::new_v5(&PROTOCOLS_NS, b"Default"),
            name: "Default".into(),
            description: "Standard structured output with a response field. \
                The simplest protocol — produces a JSON object with a single \
                response string. Use when no specialized routing or decomposition \
                is needed."
                .into(),
            protocol_type: "default".into(),
            config: serde_json::json!({
                "output_schema": {
                    "type": "object",
                    "required": ["response"],
                    "properties": {
                        "response": { "type": "string" }
                    },
                    "additionalProperties": false
                }
            }),
        },
    ]
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn returns_five_definitions() {
        let defs = builtin_protocol_definitions();
        assert_eq!(defs.len(), 5);
    }

    #[test]
    fn all_names_unique() {
        let defs = builtin_protocol_definitions();
        let names: HashSet<&str> = defs.iter().map(|d| d.name.as_str()).collect();
        assert_eq!(names.len(), 5);
    }

    #[test]
    fn all_ids_deterministic_and_unique() {
        let defs1 = builtin_protocol_definitions();
        let defs2 = builtin_protocol_definitions();
        for (a, b) in defs1.iter().zip(defs2.iter()) {
            assert_eq!(a.id, b.id);
        }
        let ids: HashSet<Uuid> = defs1.iter().map(|d| d.id).collect();
        assert_eq!(ids.len(), 5);
    }

    #[test]
    fn all_protocol_types_match_expander_keys() {
        let defs = builtin_protocol_definitions();
        let expected_types = ["decomp", "route", "review", "transform", "default"];
        let actual_types: Vec<&str> = defs.iter().map(|d| d.protocol_type.as_str()).collect();
        assert_eq!(actual_types, expected_types);
    }

    #[test]
    fn all_descriptions_non_empty() {
        for def in builtin_protocol_definitions() {
            assert!(
                !def.description.is_empty(),
                "{} has empty description",
                def.name
            );
        }
    }

    #[test]
    fn review_has_decisions_config() {
        let defs = builtin_protocol_definitions();
        let review = defs.iter().find(|d| d.protocol_type == "review").unwrap();
        let decisions = review.config["decisions"].as_array().unwrap();
        assert_eq!(decisions.len(), 3);
        assert!(decisions.contains(&serde_json::json!("approve")));
        assert!(decisions.contains(&serde_json::json!("reject")));
        assert!(decisions.contains(&serde_json::json!("revise")));
    }

    #[test]
    fn default_has_output_schema_in_config() {
        let defs = builtin_protocol_definitions();
        let default = defs.iter().find(|d| d.protocol_type == "default").unwrap();
        let schema = default.config.get("output_schema").unwrap();
        assert_eq!(schema["type"], "object");
        assert!(schema["required"]
            .as_array()
            .unwrap()
            .contains(&serde_json::json!("response")));
    }
}
