//! Output types for the documenter strategy LLM (Phase 1).
//!
//! These types are deserialized from the Phase 1 structured JSON response
//! and drive the Research (Phase 2) and Write (Phase 3) stages.

use serde::{Deserialize, Deserializer};

/// Parsed output from the strategy LLM (Phase 1).
///
/// Contains one plan per requested document, each specifying how to
/// research and write that document.
#[derive(Debug, Clone, Deserialize)]
pub struct StrategyOutput {
    pub document_plans: Vec<DocumentPlan>,
}

/// A single document's research and writing plan.
///
/// Generated by the strategy LLM, consumed by the executor to drive
/// capability resolution (Phase 2) and writer prompt composition (Phase 3).
#[derive(Debug, Clone, Deserialize)]
pub struct DocumentPlan {
    /// Must match a document definition name from the protocol config.
    pub document_name: String,
    /// Step-by-step plan for gathering the information needed.
    /// Accepts either a plain string or an array of strings (joined with newlines).
    #[serde(deserialize_with = "string_or_vec")]
    pub research_strategy: String,
    /// Capability keys the researcher needs (e.g. `["web_search", "code_analysis"]`).
    pub required_capabilities: Vec<String>,
    /// Detailed instructions for the writer: tone, structure, focus areas.
    pub writer_prompt: String,
    /// Short IDs (first 8 chars of UUID) of context documents assigned to this plan.
    /// Empty means no routing was specified (all available context documents are used).
    #[serde(default)]
    pub context_document_ids: Vec<String>,
}

/// Deserialize a value that may be a string or an array of strings.
/// If an array, the elements are joined with newlines.
fn string_or_vec<'de, D>(deserializer: D) -> Result<String, D::Error>
where
    D: Deserializer<'de>,
{
    #[derive(Deserialize)]
    #[serde(untagged)]
    enum StringOrVec {
        String(String),
        Vec(Vec<String>),
    }

    match StringOrVec::deserialize(deserializer)? {
        StringOrVec::String(s) => Ok(s),
        StringOrVec::Vec(v) => Ok(v.join("\n")),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_valid_strategy_output() {
        let json = r#"{
            "document_plans": [
                {
                    "document_name": "API Reference",
                    "research_strategy": "Analyze the API routes in src/server/api/",
                    "required_capabilities": ["code_analysis", "file_read"],
                    "writer_prompt": "Write a comprehensive REST API reference."
                },
                {
                    "document_name": "Architecture Guide",
                    "research_strategy": "Review the module structure and data flow.",
                    "required_capabilities": ["code_analysis"],
                    "writer_prompt": "Write a system architecture overview."
                }
            ]
        }"#;

        let output: StrategyOutput = serde_json::from_str(json).unwrap();
        assert_eq!(output.document_plans.len(), 2);
        assert_eq!(output.document_plans[0].document_name, "API Reference");
        assert_eq!(output.document_plans[0].required_capabilities.len(), 2);
        assert_eq!(output.document_plans[1].document_name, "Architecture Guide");
        assert_eq!(
            output.document_plans[1].writer_prompt,
            "Write a system architecture overview."
        );
    }

    #[test]
    fn parse_empty_capabilities() {
        let json = r#"{
            "document_plans": [
                {
                    "document_name": "README",
                    "research_strategy": "Use only the provided context.",
                    "required_capabilities": [],
                    "writer_prompt": "Write a project README."
                }
            ]
        }"#;

        let output: StrategyOutput = serde_json::from_str(json).unwrap();
        assert_eq!(output.document_plans.len(), 1);
        assert!(output.document_plans[0].required_capabilities.is_empty());
    }

    #[test]
    fn parse_with_context_document_ids() {
        let json = r#"{
            "document_plans": [
                {
                    "document_name": "API Reference",
                    "research_strategy": "Analyze the API routes.",
                    "required_capabilities": ["code_analysis"],
                    "writer_prompt": "Write API docs.",
                    "context_document_ids": ["550e8400", "a1b2c3d4"]
                }
            ]
        }"#;

        let output: StrategyOutput = serde_json::from_str(json).unwrap();
        assert_eq!(output.document_plans[0].context_document_ids.len(), 2);
        assert_eq!(output.document_plans[0].context_document_ids[0], "550e8400");
    }

    #[test]
    fn parse_without_context_document_ids_defaults_to_empty() {
        let json = r#"{
            "document_plans": [
                {
                    "document_name": "README",
                    "research_strategy": "Use context.",
                    "required_capabilities": [],
                    "writer_prompt": "Write a README."
                }
            ]
        }"#;

        let output: StrategyOutput = serde_json::from_str(json).unwrap();
        assert!(output.document_plans[0].context_document_ids.is_empty());
    }

    #[test]
    fn parse_research_strategy_as_array() {
        let json = r#"{
            "document_plans": [
                {
                    "document_name": "Overview",
                    "research_strategy": [
                        "Analyze the codebase structure",
                        "Review existing documentation",
                        "Identify key patterns"
                    ],
                    "required_capabilities": [],
                    "writer_prompt": "Write an overview."
                }
            ]
        }"#;

        let output: StrategyOutput = serde_json::from_str(json).unwrap();
        assert!(output.document_plans[0]
            .research_strategy
            .contains("Analyze the codebase structure"));
        assert!(output.document_plans[0]
            .research_strategy
            .contains("Identify key patterns"));
        assert!(output.document_plans[0].research_strategy.contains('\n'));
    }

    #[test]
    fn parse_rejects_missing_fields() {
        let json = r#"{
            "document_plans": [
                {
                    "document_name": "Incomplete"
                }
            ]
        }"#;

        let result = serde_json::from_str::<StrategyOutput>(json);
        assert!(result.is_err());
    }
}
