//! Output types for the documenter strategy LLM (Phase 1).
//!
//! These types are deserialized from the Phase 1 structured JSON response
//! and drive the Research (Phase 2) and Write (Phase 3) stages.

use serde::Deserialize;

/// Parsed output from the strategy LLM (Phase 1).
///
/// Contains one plan per requested document, each specifying how to
/// research and write that document.
#[derive(Debug, Clone, Deserialize)]
pub struct StrategyOutput {
    pub document_plans: Vec<DocumentPlan>,
}

/// A single document's research and writing plan.
///
/// Generated by the strategy LLM, consumed by the executor to drive
/// capability resolution (Phase 2) and writer prompt composition (Phase 3).
#[derive(Debug, Clone, Deserialize)]
pub struct DocumentPlan {
    /// Must match a document definition name from the protocol config.
    pub document_name: String,
    /// Step-by-step plan for gathering the information needed.
    pub research_strategy: String,
    /// Capability keys the researcher needs (e.g. `["web_search", "code_analysis"]`).
    pub required_capabilities: Vec<String>,
    /// Detailed instructions for the writer: tone, structure, focus areas.
    pub writer_prompt: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_valid_strategy_output() {
        let json = r#"{
            "document_plans": [
                {
                    "document_name": "API Reference",
                    "research_strategy": "Analyze the API routes in src/server/api/",
                    "required_capabilities": ["code_analysis", "file_read"],
                    "writer_prompt": "Write a comprehensive REST API reference."
                },
                {
                    "document_name": "Architecture Guide",
                    "research_strategy": "Review the module structure and data flow.",
                    "required_capabilities": ["code_analysis"],
                    "writer_prompt": "Write a system architecture overview."
                }
            ]
        }"#;

        let output: StrategyOutput = serde_json::from_str(json).unwrap();
        assert_eq!(output.document_plans.len(), 2);
        assert_eq!(output.document_plans[0].document_name, "API Reference");
        assert_eq!(output.document_plans[0].required_capabilities.len(), 2);
        assert_eq!(output.document_plans[1].document_name, "Architecture Guide");
        assert_eq!(
            output.document_plans[1].writer_prompt,
            "Write a system architecture overview."
        );
    }

    #[test]
    fn parse_empty_capabilities() {
        let json = r#"{
            "document_plans": [
                {
                    "document_name": "README",
                    "research_strategy": "Use only the provided context.",
                    "required_capabilities": [],
                    "writer_prompt": "Write a project README."
                }
            ]
        }"#;

        let output: StrategyOutput = serde_json::from_str(json).unwrap();
        assert_eq!(output.document_plans.len(), 1);
        assert!(output.document_plans[0].required_capabilities.is_empty());
    }

    #[test]
    fn parse_rejects_missing_fields() {
        let json = r#"{
            "document_plans": [
                {
                    "document_name": "Incomplete"
                }
            ]
        }"#;

        let result = serde_json::from_str::<StrategyOutput>(json);
        assert!(result.is_err());
    }
}
