import { store } from './_store'
import {
  selectSession,
  selectMessages,
  selectSegments,
  selectPanel,
  selectLoading,
  selectError,
  selectStreaming,
} from './selectors'
import {
  initStep,
  initEmpty,
  setSession,
  setSessionCreated,
  setError,
  resetStep,
  loadSession,
  clearMessages,
} from './sessions'
import {
  appendMessage,
  streamToken,
  addTool,
  completeTool,
  addDoc,
  setPanel,
  dismissPanel,
  setStreaming,
  finalizeStream,
  handleStreamError,
  handleSSEEvent,
  buildDeduplicatingHandler,
  parseTokenText,
} from './streaming'

export const assistantSessionStore = {
  store,
  selectSession,
  selectMessages,
  selectSegments,
  selectPanel,
  selectLoading,
  selectError,
  selectStreaming,
  initStep,
  initEmpty,
  setSession,
  setSessionCreated,
  setError,
  resetStep,
  loadSession,
  clearMessages,
  appendMessage,
  streamToken,
  addTool,
  completeTool,
  addDoc,
  setPanel,
  dismissPanel,
  setStreaming,
  finalizeStream,
  handleStreamError,
  handleSSEEvent,
  buildDeduplicatingHandler,
  parseTokenText,
}

export type { PanelState, StepSession, AssistantSessionState } from './types'
