import { store } from './_store'
import {
  selectAll,
  selectById,
  selectActiveWorkflowId,
  selectSteps,
  selectEdges,
  selectStepById,
  selectEdgeById,
  selectStepDocuments,
  selectStepRoster,
  selectRosterByStep,
  selectRoomStepMembers,
  selectRoomMembersByStep,
  selectPlanByStep,
  selectLoading,
  selectError,
  selectDirty,
  selectDirtyStepIds,
  selectRosterAgentById,
  selectRoomMemberById,
  selectStepQuestionState,
  selectIsStale,
} from './selectors'
import { fetchAll, fetchIfStale, fetchOne, create, update, remove, loadWorkflow, clearActive, upsert, setDirty } from './workflows'
import { createStep, patchStepLocal, patchStepSilent, updateStep, deleteStep, removeStepLocal, saveAllDirtySteps, revertSteps } from './steps'
import { addEdge, removeEdge } from './edges'
import { fetchStepDocuments, addStepDocument, removeStepDocument } from './documents'
import { fetchRoster, createRosterAgent, deleteRosterAgent, fetchRoomStepMembers } from './roster'
import { fetchAllPlans } from './plans'
import { fetchQuestionStates } from './questionStates'
import { handleWsEvent } from './wsHandler'

export const workflowStore = {
  store,
  selectAll,
  selectById,
  selectActiveWorkflowId,
  selectSteps,
  selectEdges,
  selectStepById,
  selectEdgeById,
  selectStepDocuments,
  selectStepRoster,
  selectRosterByStep,
  selectRoomStepMembers,
  selectRoomMembersByStep,
  selectPlanByStep,
  selectLoading,
  selectError,
  selectDirty,
  selectDirtyStepIds,
  selectRosterAgentById,
  selectRoomMemberById,
  selectStepQuestionState,
  selectIsStale,
  fetchAll,
  fetchIfStale,
  fetchOne,
  create,
  update,
  remove,
  loadWorkflow,
  clearActive,
  createStep,
  patchStepLocal,
  patchStepSilent,
  updateStep,
  saveAllDirtySteps,
  revertSteps,
  deleteStep,
  removeStepLocal,
  addEdge,
  removeEdge,
  fetchStepDocuments,
  addStepDocument,
  removeStepDocument,
  fetchRoster,
  createRosterAgent,
  deleteRosterAgent,
  fetchRoomStepMembers,
  fetchAllPlans,
  fetchQuestionStates,
  handleWsEvent,
  setDirty,
  upsert,
}

export type { WorkflowState } from './types'
