import { store } from './_store'
import {
  selectAll,
  selectById,
  selectActiveWorkflowId,
  selectSteps,
  selectEdges,
  selectStepById,
  selectEdgeById,
  selectStepDocuments,
  selectStepDocumentDefs,
  selectDocumentDefsByStep,
  selectStepRoster,
  selectRosterByStep,
  selectRoomStepMembers,
  selectRoomMembersByStep,
  selectNotesByStep,
  selectDocumentContentByDefId,
  selectLoading,
  selectError,
  selectDirty,
  selectDirtyStepIds,
  selectIsStale,
} from './selectors'
import { fetchAll, fetchIfStale, fetchOne, create, update, remove, loadWorkflow, clearActive, upsert, setDirty } from './workflows'
import { createStep, patchStepLocal, patchStepSilent, updateStep, deleteStep, saveAllDirtySteps, revertSteps } from './steps'
import { addEdge, removeEdge } from './edges'
import {
  fetchStepDocuments,
  addStepDocument,
  removeStepDocument,
  fetchDocumentDefs,
  createDocumentDef,
  deleteDocumentDef,
  fetchDocumentContent,
} from './documents'
import { fetchRoster, createRosterAgent, deleteRosterAgent, fetchRoomStepMembers } from './roster'
import { fetchAllNotes } from './notes'
import { handleWsEvent } from './wsHandler'

export const workflowStore = {
  store,
  selectAll,
  selectById,
  selectActiveWorkflowId,
  selectSteps,
  selectEdges,
  selectStepById,
  selectEdgeById,
  selectStepDocuments,
  selectStepDocumentDefs,
  selectDocumentDefsByStep,
  selectStepRoster,
  selectRosterByStep,
  selectRoomStepMembers,
  selectRoomMembersByStep,
  selectNotesByStep,
  selectDocumentContentByDefId,
  selectLoading,
  selectError,
  selectDirty,
  selectDirtyStepIds,
  selectIsStale,
  fetchAll,
  fetchIfStale,
  fetchOne,
  create,
  update,
  remove,
  loadWorkflow,
  clearActive,
  createStep,
  patchStepLocal,
  patchStepSilent,
  updateStep,
  saveAllDirtySteps,
  revertSteps,
  deleteStep,
  addEdge,
  removeEdge,
  fetchStepDocuments,
  addStepDocument,
  removeStepDocument,
  fetchDocumentDefs,
  createDocumentDef,
  deleteDocumentDef,
  fetchDocumentContent,
  fetchRoster,
  createRosterAgent,
  deleteRosterAgent,
  fetchRoomStepMembers,
  fetchAllNotes,
  handleWsEvent,
  setDirty,
  upsert,
}

export type { WorkflowState } from './types'
