export { computePlacements } from './placementEngine'
export { usePlacementEngine } from './usePlacementEngine'
export { placeFanOutGroup, placeConvergenceTarget } from './fanOutPlacer'
export { placeSpliceNode } from './splicePlacer'
export { PLACEMENT } from './constants'
export type { PlacementIntent, PlacementResult, PlacementShift, PlacementOutput, PlacementStrategy, OccupiedRect, SpliceResult } from './types'
