//! Persistent Docker container management for agent step execution.
//!
//! Each DAG step can optionally execute inside its own Docker container with a
//! cloned GitHub repo. The container stays alive across all tool calls within
//! the step, then is destroyed when the step completes.

use std::fmt;
use std::process::Stdio;
use std::sync::Arc;

use async_trait::async_trait;
use once_cell::sync::Lazy;
use thiserror::Error;
use tokio::process::Command;
use tokio::sync::Semaphore;
use tracing::{debug, info, trace, warn};
use uuid::Uuid;

pub mod overlay;
pub mod retry;
#[cfg(test)]
mod tests;

// ── Docker CLI Abstraction ───────────────────────────────────────────────

/// Raw output from a Docker CLI invocation.
#[derive(Debug, Clone)]
pub struct CommandOutput {
    pub exit_code: i32,
    pub stdout: Vec<u8>,
    pub stderr: Vec<u8>,
}

/// Abstraction over Docker CLI commands for testability.
///
/// Production code uses [`RealDockerCli`] which spawns `tokio::process::Command`.
/// Tests use `MockDockerCli` generated by mockall.
#[cfg_attr(test, mockall::automock)]
#[async_trait]
pub trait DockerCli: Send + Sync {
    /// Run `docker <args>` and capture output.
    async fn run(&self, args: Vec<String>) -> std::io::Result<CommandOutput>;

    /// Run `docker <args>` piping `stdin_data` to stdin and capture output.
    async fn run_with_stdin(
        &self,
        args: Vec<String>,
        stdin_data: Vec<u8>,
    ) -> std::io::Result<CommandOutput>;
}

/// Production implementation that spawns real Docker processes.
#[derive(Debug, Clone)]
pub struct RealDockerCli;

#[async_trait]
impl DockerCli for RealDockerCli {
    async fn run(&self, args: Vec<String>) -> std::io::Result<CommandOutput> {
        let output = Command::new("docker")
            .args(&args)
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .output()
            .await?;
        Ok(CommandOutput {
            exit_code: output.status.code().unwrap_or(-1),
            stdout: output.stdout,
            stderr: output.stderr,
        })
    }

    async fn run_with_stdin(
        &self,
        args: Vec<String>,
        stdin_data: Vec<u8>,
    ) -> std::io::Result<CommandOutput> {
        let mut child = Command::new("docker")
            .args(&args)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()?;

        if let Some(mut stdin) = child.stdin.take() {
            use tokio::io::AsyncWriteExt;
            stdin.write_all(&stdin_data).await?;
            drop(stdin);
        }

        let output = child.wait_with_output().await?;
        Ok(CommandOutput {
            exit_code: output.status.code().unwrap_or(-1),
            stdout: output.stdout,
            stderr: output.stderr,
        })
    }
}

// ── RedactedString ────────────────────────────────────────────────────────

/// A string that hides its value in Debug/Display output.
///
/// Use `.expose()` to access the inner value when you need it
/// (e.g., for constructing authenticated URLs or env vars).
#[derive(Clone, Default)]
pub struct RedactedString(String);

impl RedactedString {
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    /// Access the inner secret value. Only use where the actual value is needed.
    pub fn expose(&self) -> &str {
        &self.0
    }

    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

impl fmt::Debug for RedactedString {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "[REDACTED]")
    }
}

impl fmt::Display for RedactedString {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "[REDACTED]")
    }
}

// ── Errors ─────────────────────────────────────────────────────────────────

#[derive(Error, Debug)]
pub enum ContainerError {
    #[error("docker not available: {0}")]
    DockerNotAvailable(String),

    #[error("container creation failed: {0}")]
    CreationFailed(String),

    #[error("repo clone failed: {stderr}")]
    CloneFailed { stderr: String },

    #[error("command failed in container {container}: exit {exit_code}: {stderr}")]
    CommandFailed {
        container: String,
        exit_code: i32,
        stderr: String,
    },

    #[error("command timed out after {timeout_secs}s in container {container}")]
    Timeout {
        container: String,
        timeout_secs: u64,
    },

    #[error("container not running: {container}")]
    NotRunning { container: String },

    #[error("path not allowed: {path} — {reason}")]
    PathNotAllowed { path: String, reason: String },

    #[error("docker {operation} failed: {source}")]
    DockerSpawnFailed {
        operation: &'static str,
        #[source]
        source: std::io::Error,
    },

    #[error("container creation timed out after {timeout_secs}s for {container}")]
    CreateTimeout {
        container: String,
        timeout_secs: u64,
    },

    #[error("network disconnect failed for container {container}: {stderr}")]
    NetworkDisconnectFailed { container: String, stderr: String },

    #[error("io error: {0}")]
    IoError(#[from] std::io::Error),
}

// ── Config ─────────────────────────────────────────────────────────────────

/// Configuration for creating a persistent agent container.
#[derive(Debug, Clone)]
pub struct ContainerConfig {
    /// Docker image (e.g., "nexor-agent:latest").
    pub image: String,
    /// GitHub repo clone URL (e.g., "https://github.com/owner/repo.git").
    pub clone_url: String,
    /// Branch to checkout after clone. None = default branch.
    pub branch: Option<String>,
    /// GitHub token for authenticated clone/push.
    pub github_token: RedactedString,
    /// Memory limit (e.g., "2g").
    pub memory_limit: String,
    /// CPU limit (e.g., "2.0").
    pub cpu_limit: String,
    /// Timeout for individual commands in seconds.
    pub command_timeout_secs: u64,
    /// Additional environment variables.
    pub env_vars: Vec<(String, String)>,
    /// Working directory inside container.
    pub workdir: String,
    /// Optional Docker network mode (e.g., "container:<vpn_sidecar_id>").
    pub network_mode: Option<String>,
    /// Whether to disconnect the container from all networks after the initial
    /// git clone. Defaults to `true`. Ignored when `network_mode` is `Some`.
    pub network_isolated: bool,
    /// Named Docker volume + subpath for workspace mount.
    /// When set: mounts the volume subpath at /workspace/, skips git clone,
    /// injects package manager env vars, and keeps network connected.
    /// When None: existing git-clone behavior (backward compatible).
    pub workspace_volume: Option<WorkspaceVolume>,
    /// Enable OverlayFS isolation for workspace writes.
    /// When true AND workspace_volume is set: JuiceFS is mounted read-only at
    /// /workspace-base, with an OverlayFS writable upper layer at /workspace.
    /// When false: existing direct mount behavior (backward compatible).
    pub overlay_enabled: bool,
}

/// Docker named volume + subpath for agent workspace mounts.
///
/// Used to mount a specific run directory from a shared JuiceFS volume
/// into the agent container at `/workspace/`.
#[derive(Debug, Clone)]
pub struct WorkspaceVolume {
    /// Docker volume name (e.g. "gh-agents_jfs-workspace").
    pub volume_name: String,
    /// Subpath within the volume (e.g. "workflows/{wf_id}/runs/{run_id}").
    pub subpath: String,
}

impl Default for ContainerConfig {
    fn default() -> Self {
        Self {
            image: crate::constants::CONTAINER_DEFAULT_IMAGE.to_string(),
            clone_url: String::new(),
            branch: None,
            github_token: RedactedString::default(),
            memory_limit: crate::constants::CONTAINER_DEFAULT_MEMORY.to_string(),
            cpu_limit: crate::constants::CONTAINER_DEFAULT_CPUS.to_string(),
            command_timeout_secs: crate::constants::CONTAINER_COMMAND_TIMEOUT_SECS,
            env_vars: Vec::new(),
            workdir: "/workspace".to_string(),
            network_mode: None,
            network_isolated: true,
            workspace_volume: None,
            overlay_enabled: false,
        }
    }
}

// ── Security Utilities ────────────────────────────────────────────────────

/// Strip a token from git stderr output to prevent credential leaks in logs/errors.
pub fn sanitize_git_output(output: &str, token: &RedactedString) -> String {
    let secret = token.expose();
    if secret.is_empty() {
        return output.to_string();
    }
    output.replace(secret, "[REDACTED]")
}

/// Escape a path for safe use inside single-quoted shell arguments.
///
/// Handles the `'` character by ending the quote, inserting an escaped quote,
/// and reopening the quote: `can't` → `'can'\''t'`
pub fn shell_escape_path(path: &str) -> String {
    if !path.contains('\'') {
        return format!("'{}'", path);
    }
    let escaped = path.replace('\'', "'\\''");
    format!("'{}'", escaped)
}

/// Deepest `list_files` will walk. A workspace holding an installed dependency
/// tree is mostly noise below this, and the noise is pruned by name rather than
/// by depth, so this is a bound on pathological nesting rather than a budget.
pub const LIST_FILES_MAX_DEPTH: u32 = 6;

/// Most entries `list_files` returns before it starts dropping them.
pub const LIST_FILES_MAX_ENTRIES: usize = 500;

/// Validate that a container path is safe (no absolute paths, no `..` traversal).
pub fn validate_container_path(path: &str) -> Result<(), ContainerError> {
    if path.starts_with('/') {
        return Err(ContainerError::PathNotAllowed {
            path: path.to_string(),
            reason: "absolute paths are not allowed".to_string(),
        });
    }
    for component in path.split('/') {
        if component == ".." {
            return Err(ContainerError::PathNotAllowed {
                path: path.to_string(),
                reason: "path traversal (..) is not allowed".to_string(),
            });
        }
    }
    Ok(())
}

/// Disconnect a container from the Docker bridge network.
///
/// Removes all network access, preventing data exfiltration after the
/// initial git clone. Idempotent: returns Ok if the container is already
/// disconnected or the network doesn't exist.
async fn disconnect_bridge_network(
    cli: &dyn DockerCli,
    container_id: &str,
    container_name: &str,
) -> Result<(), ContainerError> {
    let output = cli
        .run(vec![
            "network".to_string(),
            "disconnect".to_string(),
            "-f".to_string(),
            "bridge".to_string(),
            container_id.to_string(),
        ])
        .await
        .map_err(|e| ContainerError::DockerSpawnFailed {
            operation: "network disconnect",
            source: e,
        })?;

    if output.exit_code != 0 {
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();
        // Docker returns an error if the container is not connected — that's fine.
        if stderr.contains("is not connected to") {
            debug!(
                container = container_name,
                "Container already disconnected from bridge"
            );
            return Ok(());
        }
        return Err(ContainerError::NetworkDisconnectFailed {
            container: container_name.to_string(),
            stderr,
        });
    }

    info!(
        container = container_name,
        "Disconnected container from bridge network (network isolated)"
    );
    Ok(())
}

// ── Exec Result ────────────────────────────────────────────────────────────

/// Result of executing a command inside a container.
#[derive(Debug, Clone)]
pub struct ContainerExecResult {
    pub success: bool,
    pub exit_code: i32,
    pub stdout: String,
    pub stderr: String,
    pub duration_ms: u64,
    /// Whether stdout or stderr was truncated due to exceeding the output size limit.
    pub truncated: bool,
}

/// Truncate raw command output to `max_bytes`, returning the string and whether truncation occurred.
fn truncate_output(raw: &[u8], max_bytes: usize) -> (String, bool) {
    if raw.len() <= max_bytes {
        return (String::from_utf8_lossy(raw).to_string(), false);
    }
    let truncated = String::from_utf8_lossy(&raw[..max_bytes]).to_string();
    (
        format!("{}\n... [truncated, {} bytes total]", truncated, raw.len()),
        true,
    )
}

// ── Handle ─────────────────────────────────────────────────────────────────

/// Handle to a running persistent container. All tool calls go through this.
#[derive(Clone)]
pub struct ContainerHandle {
    container_id: String,
    container_name: String,
    workdir: String,
    command_timeout_secs: u64,
    cli: Arc<dyn DockerCli>,
}

impl fmt::Debug for ContainerHandle {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("ContainerHandle")
            .field("container_id", &self.container_id)
            .field("container_name", &self.container_name)
            .field("workdir", &self.workdir)
            .field("command_timeout_secs", &self.command_timeout_secs)
            .finish()
    }
}

impl ContainerHandle {
    /// Get the container name (for logging).
    pub fn container_name(&self) -> &str {
        &self.container_name
    }

    /// Execute a command inside the container via `docker exec`.
    pub async fn exec(&self, command: &[&str]) -> Result<ContainerExecResult, ContainerError> {
        let start = std::time::Instant::now();

        let mut docker_args: Vec<String> = vec![
            "exec".to_string(),
            "-w".to_string(),
            self.workdir.clone(),
            self.container_id.clone(),
        ];
        docker_args.extend(command.iter().map(|s| s.to_string()));

        let output = tokio::time::timeout(
            std::time::Duration::from_secs(self.command_timeout_secs),
            self.cli.run(docker_args),
        )
        .await;

        let duration_ms = start.elapsed().as_millis() as u64;

        match output {
            Ok(Ok(cmd_output)) => {
                let max = crate::constants::CONTAINER_MAX_OUTPUT_BYTES;
                let (stdout, stdout_truncated) = truncate_output(&cmd_output.stdout, max);
                let (stderr, stderr_truncated) = truncate_output(&cmd_output.stderr, max);
                let truncated = stdout_truncated || stderr_truncated;

                if truncated {
                    warn!(
                        container = %self.container_name,
                        stdout_bytes = cmd_output.stdout.len(),
                        stderr_bytes = cmd_output.stderr.len(),
                        max_bytes = max,
                        "Container output truncated"
                    );
                }

                let result = ContainerExecResult {
                    success: cmd_output.exit_code == 0,
                    exit_code: cmd_output.exit_code,
                    stdout,
                    stderr,
                    duration_ms,
                    truncated,
                };
                trace!(
                    container = %self.container_name,
                    exit_code = result.exit_code,
                    duration_ms,
                    "Container exec completed"
                );
                Ok(result)
            }
            Ok(Err(e)) => Err(ContainerError::DockerSpawnFailed {
                operation: "exec",
                source: e,
            }),
            Err(_) => {
                warn!(
                    container = %self.container_name,
                    timeout_secs = self.command_timeout_secs,
                    "Container command timed out"
                );
                Err(ContainerError::Timeout {
                    container: self.container_name.clone(),
                    timeout_secs: self.command_timeout_secs,
                })
            }
        }
    }

    /// Execute a shell command via `docker exec sh -c "..."`.
    pub async fn exec_shell(&self, shell_cmd: &str) -> Result<ContainerExecResult, ContainerError> {
        self.exec(&["sh", "-c", shell_cmd]).await
    }

    /// Execute a command and return raw stdout bytes (no UTF-8 conversion).
    ///
    /// Used for reading binary file content (e.g., overlay diff extraction)
    /// where lossy UTF-8 conversion would corrupt the data.
    /// Returns `(stdout_bytes, success, exit_code)`.
    pub async fn exec_raw(&self, command: &[&str]) -> Result<(Vec<u8>, bool, i32), ContainerError> {
        let mut docker_args: Vec<String> = vec![
            "exec".to_string(),
            "-w".to_string(),
            self.workdir.clone(),
            self.container_id.clone(),
        ];
        docker_args.extend(command.iter().map(|s| s.to_string()));

        let output = tokio::time::timeout(
            std::time::Duration::from_secs(self.command_timeout_secs),
            self.cli.run(docker_args),
        )
        .await;

        match output {
            Ok(Ok(cmd_output)) => Ok((
                cmd_output.stdout,
                cmd_output.exit_code == 0,
                cmd_output.exit_code,
            )),
            Ok(Err(e)) => Err(ContainerError::DockerSpawnFailed {
                operation: "exec",
                source: e,
            }),
            Err(_) => Err(ContainerError::Timeout {
                container: self.container_name.clone(),
                timeout_secs: self.command_timeout_secs,
            }),
        }
    }

    /// Read a file from the container.
    pub async fn read_file(&self, path: &str) -> Result<String, ContainerError> {
        let result = self.exec(&["cat", path]).await?;
        if !result.success {
            return Err(ContainerError::CommandFailed {
                container: self.container_name.clone(),
                exit_code: result.exit_code,
                stderr: result.stderr,
            });
        }
        Ok(result.stdout)
    }

    /// Write a file inside the container by piping content through stdin.
    pub async fn write_file(&self, path: &str, content: &str) -> Result<(), ContainerError> {
        // Ensure parent directory exists
        if let Some(parent) = std::path::Path::new(path).parent() {
            if parent != std::path::Path::new("") && parent != std::path::Path::new("/") {
                let mkdir_cmd = format!(
                    "mkdir -p {}",
                    shell_escape_path(&parent.display().to_string())
                );
                self.exec_shell(&mkdir_cmd).await?;
            }
        }

        // Write via stdin pipe
        let args = vec![
            "exec".to_string(),
            "-i".to_string(),
            "-w".to_string(),
            self.workdir.clone(),
            self.container_id.clone(),
            "sh".to_string(),
            "-c".to_string(),
            format!("cat > {}", shell_escape_path(path)),
        ];

        let cmd_output = self
            .cli
            .run_with_stdin(args, content.as_bytes().to_vec())
            .await
            .map_err(|e| ContainerError::DockerSpawnFailed {
                operation: "exec (write_file)",
                source: e,
            })?;

        if cmd_output.exit_code != 0 {
            return Err(ContainerError::CommandFailed {
                container: self.container_name.clone(),
                exit_code: cmd_output.exit_code,
                stderr: String::from_utf8_lossy(&cmd_output.stderr).to_string(),
            });
        }

        Ok(())
    }

    /// List files under a directory inside the container, walking down to
    /// `max_depth` levels.
    ///
    /// Returns paths relative to `path`, sorted, with a trailing `/` on every
    /// directory. Skips the same things the passdown manifest skips — any
    /// component starting with `.`, plus node_modules, __pycache__ and
    /// site-packages — so a workspace with an installed dependency tree in it
    /// still returns a readable listing.
    ///
    /// Recursive because a deliverable can be a directory. `ls -1a`, which this
    /// replaces, returned one level with no way to tell a directory from a
    /// file, so an agent handed a tree needed one call per level and could not
    /// tell which entries were worth descending into.
    ///
    /// Caps at `LIST_FILES_MAX_ENTRIES`; the count of what was dropped comes
    /// back alongside so the caller can say so rather than silently truncating.
    pub async fn list_files(
        &self,
        path: &str,
        max_depth: u32,
    ) -> Result<(Vec<String>, usize), ContainerError> {
        let quoted = shell_escape_path(path);
        let depth = max_depth.clamp(1, LIST_FILES_MAX_DEPTH);

        // One `find`, because the alternative is a call per directory level.
        // `-mindepth 1` keeps the start directory itself from being tested
        // against the `.*` prune pattern, which would prune the whole search.
        // The `while` loop is what marks directories: `find` has no portable
        // way to print a type suffix, and knowing which entries are worth
        // descending into is the point of the listing.
        let cmd = format!(
            "find {quoted} -mindepth 1 -maxdepth {depth} \
             \\( -name '.*' -o -name node_modules -o -name __pycache__ \
             -o -name site-packages \\) -prune -o -print \
             | while IFS= read -r p; do \
             if [ -d \"$p\" ]; then printf '%s/\\n' \"$p\"; \
             else printf '%s\\n' \"$p\"; fi; done \
             | LC_ALL=C sort"
        );

        let result = self.exec_shell(&cmd).await?;
        if !result.success {
            return Err(ContainerError::CommandFailed {
                container: self.container_name.clone(),
                exit_code: result.exit_code,
                stderr: result.stderr,
            });
        }

        let prefix = format!("{}/", path.trim_end_matches('/'));
        let mut entries: Vec<String> = result
            .stdout
            .lines()
            .filter(|l| !l.is_empty())
            .map(|l| l.strip_prefix(&prefix).unwrap_or(l).to_string())
            .filter(|l| !l.is_empty())
            .collect();

        let dropped = entries.len().saturating_sub(LIST_FILES_MAX_ENTRIES);
        entries.truncate(LIST_FILES_MAX_ENTRIES);
        Ok((entries, dropped))
    }

    /// Run a git command inside the container.
    pub async fn git(&self, args: &[&str]) -> Result<String, ContainerError> {
        let mut cmd = vec!["git"];
        cmd.extend(args);
        let result = self.exec(&cmd).await?;
        if !result.success {
            return Err(ContainerError::CommandFailed {
                container: self.container_name.clone(),
                exit_code: result.exit_code,
                stderr: result.stderr,
            });
        }
        Ok(result.stdout)
    }

    /// Check if the container is still running.
    pub async fn is_alive(&self) -> bool {
        let args = vec![
            "inspect".to_string(),
            "--format={{.State.Running}}".to_string(),
            self.container_id.clone(),
        ];
        match self.cli.run(args).await {
            Ok(o) => String::from_utf8_lossy(&o.stdout).trim() == "true",
            Err(_) => false,
        }
    }
}

// ── Manager ────────────────────────────────────────────────────────────────

/// Global semaphore limiting concurrent container creation operations.
///
/// Prevents Docker daemon resource exhaustion when for-each pipelines
/// attempt to create many containers simultaneously.
static CONTAINER_CREATE_SEMAPHORE: Lazy<Arc<Semaphore>> = Lazy::new(|| {
    Arc::new(Semaphore::new(
        crate::constants::CONTAINER_MAX_CONCURRENT_CREATES,
    ))
});

/// Environment variables injected when a workspace mount is active.
/// Download caches go to /tmp/ to avoid polluting the overlay.
///
/// `PATH` carries the two install prefixes that are redirected into the
/// workspace. Without it the redirect only half works: `npm install -g foo`
/// puts the binary at `/workspace/.npm/bin/foo`, it survives into the next
/// step because the workspace does — and the next step's agent types `foo`
/// and gets "command not found". The prompts tell agents these installs
/// persist; this is what makes that true.
const WORKSPACE_ENV_VARS: &[(&str, &str)] = &[
    ("PIP_CACHE_DIR", "/tmp/pip-cache"),
    ("PYTHONDONTWRITEBYTECODE", "1"),
    ("npm_config_prefix", "/workspace/.npm"),
    ("npm_config_cache", "/tmp/npm-cache"),
    ("CARGO_HOME", "/workspace/.cargo"),
    ("XDG_CACHE_HOME", "/tmp/cache"),
    (
        "PATH",
        "/workspace/.npm/bin:/workspace/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    ),
];

/// Build the `docker create` arguments for a container.
///
/// Separated for testability — security and resource flags are validated by unit tests.
fn build_create_args(container_name: &str, config: &ContainerConfig) -> Vec<String> {
    let mut args = vec![
        "create".to_string(),
        "--name".to_string(),
        container_name.to_string(),
        format!("--memory={}", config.memory_limit),
        format!("--cpus={}", config.cpu_limit),
        "--cap-drop=ALL".to_string(),
        "--security-opt=no-new-privileges".to_string(),
        "-w".to_string(),
        config.workdir.clone(),
        format!("--env=GITHUB_TOKEN={}", config.github_token.expose()),
    ];
    for (k, v) in &config.env_vars {
        args.push(format!("--env={}={}", k, v));
    }
    // Workspace volume: mount named volume subpath + inject package manager env vars
    if let Some(ref vol) = config.workspace_volume {
        if config.overlay_enabled {
            // Overlay mode: JuiceFS at /workspace-base, overlay at /workspace.
            // No Docker readonly flag — OverlayFS naturally redirects all writes
            // to the upper layer. The Docker readonly flag blocks the overlay mount
            // syscall on some kernels ("cannot mount overlay read-only").
            args.push("--mount".to_string());
            args.push(format!(
                "type=volume,source={},target={},volume-subpath={}",
                vol.volume_name,
                crate::constants::OVERLAY_LOWER_DIR,
                vol.subpath
            ));
            // Capabilities needed for overlay mount after cap-drop=ALL:
            // SYS_ADMIN: mount syscall
            // DAC_OVERRIDE + DAC_READ_SEARCH: traverse and read lower dir
            args.push("--cap-add=SYS_ADMIN".to_string());
            args.push("--cap-add=DAC_OVERRIDE".to_string());
            args.push("--cap-add=DAC_READ_SEARCH".to_string());
        } else {
            // Direct mode: JuiceFS at /workspace (existing behavior)
            args.push("--mount".to_string());
            args.push(format!(
                "type=volume,source={},target=/workspace,volume-subpath={}",
                vol.volume_name, vol.subpath
            ));
        }
        for (k, v) in WORKSPACE_ENV_VARS {
            args.push(format!("--env={}={}", k, v));
        }
    }
    if let Some(ref network) = config.network_mode {
        args.push(format!("--network={}", network));
    }
    args.push(config.image.clone());
    args.push("sleep".to_string());
    args.push("infinity".to_string());
    args
}

/// Creates and destroys persistent Docker containers for agent steps.
#[derive(Clone)]
pub struct ContainerManager {
    cli: Arc<dyn DockerCli>,
}

impl ContainerManager {
    /// Create a new ContainerManager with the given Docker CLI implementation.
    pub fn new(cli: Arc<dyn DockerCli>) -> Self {
        Self { cli }
    }

    /// Create a ContainerManager using the real Docker CLI.
    pub fn real() -> Self {
        Self::new(Arc::new(RealDockerCli))
    }

    /// Create and start a persistent container, then clone the repo into it.
    ///
    /// Acquires a creation semaphore permit (queues if at capacity), then wraps
    /// the entire creation flow in a timeout. On timeout, attempts cleanup of
    /// the partially-created container.
    pub async fn create_container(
        &self,
        config: &ContainerConfig,
    ) -> Result<ContainerHandle, ContainerError> {
        // Acquire creation semaphore (queue if at capacity)
        let _permit = CONTAINER_CREATE_SEMAPHORE
            .acquire()
            .await
            .expect("container creation semaphore closed");

        let timeout_secs = crate::constants::CONTAINER_CREATE_TIMEOUT_SECS;
        let timeout_duration = std::time::Duration::from_secs(timeout_secs);

        // Generate name before timeout so we can reference it in cleanup
        let container_name = format!(
            "{}-{}",
            crate::constants::CONTAINER_NAME_PREFIX,
            Uuid::new_v4()
        );
        let name_for_cleanup = container_name.clone();
        let cli = self.cli.clone();

        let result = tokio::time::timeout(
            timeout_duration,
            self.create_container_inner(config, container_name),
        )
        .await;

        match result {
            Ok(inner_result) => inner_result,
            Err(_elapsed) => {
                warn!(
                    container = %name_for_cleanup,
                    timeout_secs,
                    "Container creation timed out, attempting cleanup"
                );
                let _ = cli
                    .run(vec![
                        "rm".to_string(),
                        "-f".to_string(),
                        name_for_cleanup.clone(),
                    ])
                    .await;
                Err(ContainerError::CreateTimeout {
                    container: name_for_cleanup,
                    timeout_secs,
                })
            }
        }
    }

    /// Inner implementation of container creation (called within a timeout).
    async fn create_container_inner(
        &self,
        config: &ContainerConfig,
        container_name: String,
    ) -> Result<ContainerHandle, ContainerError> {
        let create_start = std::time::Instant::now();

        info!(container = %container_name, image = %config.image, "Creating persistent container");

        // 1. docker create
        let create_args = build_create_args(&container_name, config);
        debug!(container = %container_name, args = ?create_args, "Docker create args");

        let create_output = self
            .cli
            .run(create_args)
            .await
            .map_err(|e| ContainerError::DockerNotAvailable(e.to_string()))?;

        if create_output.exit_code != 0 {
            return Err(ContainerError::CreationFailed(
                String::from_utf8_lossy(&create_output.stderr)
                    .trim()
                    .to_string(),
            ));
        }

        let container_id = String::from_utf8_lossy(&create_output.stdout)
            .trim()
            .to_string();

        // 2. docker start
        let start_output = self
            .cli
            .run(vec!["start".to_string(), container_id.clone()])
            .await
            .map_err(|e| ContainerError::DockerSpawnFailed {
                operation: "start",
                source: e,
            })?;

        if start_output.exit_code != 0 {
            let _ = self
                .cli
                .run(vec![
                    "rm".to_string(),
                    "-f".to_string(),
                    container_id.clone(),
                ])
                .await;
            return Err(ContainerError::CreationFailed(
                "Failed to start container".to_string(),
            ));
        }

        let handle = ContainerHandle {
            container_id: container_id.clone(),
            container_name: container_name.clone(),
            workdir: config.workdir.clone(),
            command_timeout_secs: config.command_timeout_secs,
            cli: self.cli.clone(),
        };

        // Workspace mode: mount provides content, no repo to clone.
        // Agent keeps network access for pip install, curl, etc.
        if let Some(ref vol) = config.workspace_volume {
            // Overlay mode: set up OverlayFS inside the container
            if config.overlay_enabled {
                if let Err(e) = overlay::setup_overlay(&handle).await {
                    Self::destroy_container_quiet(&handle).await;
                    return Err(ContainerError::CreationFailed(format!(
                        "OverlayFS setup failed: {}",
                        e
                    )));
                }
                info!(
                    container = %container_name,
                    "OverlayFS mounted: {} (lower) → {} (merged)",
                    crate::constants::OVERLAY_LOWER_DIR,
                    crate::constants::OVERLAY_MERGED_DIR,
                );
            }

            let create_duration_ms = create_start.elapsed().as_millis() as u64;
            info!(
                container = %container_name,
                volume = %vol.volume_name,
                subpath = %vol.subpath,
                overlay = config.overlay_enabled,
                duration_ms = create_duration_ms,
                "Container ready with workspace mount"
            );
            return Ok(handle);
        }

        // 3. Clone repository
        let clone_url = format!(
            "https://x-access-token:{}@{}",
            config.github_token.expose(),
            config.clone_url.trim_start_matches("https://")
        );
        let clone_result = handle
            .exec(&["git", "clone", "--depth=1", &clone_url, "."])
            .await;
        match clone_result {
            Ok(r) if !r.success => {
                Self::destroy_container_quiet(&handle).await;
                return Err(ContainerError::CloneFailed {
                    stderr: sanitize_git_output(&r.stderr, &config.github_token),
                });
            }
            Err(e) => {
                Self::destroy_container_quiet(&handle).await;
                return Err(e);
            }
            _ => {}
        }

        // 4. Checkout branch if specified
        if let Some(ref branch) = config.branch {
            let checkout_result = handle.exec(&["git", "checkout", branch]).await;
            if let Ok(r) = &checkout_result {
                if !r.success {
                    // Try fetching the remote branch
                    let _ = handle.exec(&["git", "fetch", "origin", branch]).await;
                    let _ = handle
                        .exec(&[
                            "git",
                            "checkout",
                            "-b",
                            branch,
                            &format!("origin/{}", branch),
                        ])
                        .await;
                }
            }
        }

        // 5. Configure git user
        let _ = handle
            .exec(&["git", "config", "user.email", "nexor@nexor.ai"])
            .await;
        let _ = handle
            .exec(&["git", "config", "user.name", "Nexor Agent"])
            .await;

        // 6. Network isolation: disconnect from bridge after clone completes
        if config.network_isolated && config.network_mode.is_none() {
            if let Err(e) =
                disconnect_bridge_network(self.cli.as_ref(), &container_id, &container_name).await
            {
                warn!(
                    container = %container_name,
                    error = %e,
                    "Failed to isolate container network — continuing with network access"
                );
            }
        }

        let create_duration_ms = create_start.elapsed().as_millis() as u64;
        info!(
            container = %container_name,
            repo = %config.clone_url,
            duration_ms = create_duration_ms,
            "Container ready with cloned repo"
        );

        Ok(handle)
    }

    /// Stop and remove a container.
    pub async fn destroy_container(handle: &ContainerHandle) -> Result<(), ContainerError> {
        let destroy_start = std::time::Instant::now();

        let rm_output = handle
            .cli
            .run(vec![
                "rm".to_string(),
                "-f".to_string(),
                handle.container_id.clone(),
            ])
            .await
            .map_err(|e| ContainerError::DockerSpawnFailed {
                operation: "rm",
                source: e,
            })?;

        if rm_output.exit_code != 0 {
            warn!(
                container = %handle.container_name,
                stderr = %String::from_utf8_lossy(&rm_output.stderr),
                "Failed to remove container"
            );
        }

        let destroy_duration_ms = destroy_start.elapsed().as_millis() as u64;
        info!(
            container = %handle.container_name,
            duration_ms = destroy_duration_ms,
            "Container destroyed"
        );

        Ok(())
    }

    /// Destroy container, ignoring errors. For cleanup in finally blocks.
    pub async fn destroy_container_quiet(handle: &ContainerHandle) {
        if let Err(e) = Self::destroy_container(handle).await {
            warn!(
                container = %handle.container_name,
                error = %e,
                "Failed to destroy container (quiet)"
            );
        }
    }

    /// Find and kill orphaned `nexor-step-*` containers older than `max_age`.
    ///
    /// Called at server startup to clean up containers left behind by crashes.
    /// Returns the number of containers reaped.
    pub async fn reap_orphaned_containers(&self, max_age: std::time::Duration) -> usize {
        let reap_start = std::time::Instant::now();

        let output = self
            .cli
            .run(vec![
                "ps".to_string(),
                "-a".to_string(),
                "--filter".to_string(),
                format!("name={}", crate::constants::CONTAINER_NAME_PREFIX),
                "--format".to_string(),
                "{{.ID}}\t{{.CreatedAt}}\t{{.Names}}".to_string(),
            ])
            .await;

        let output = match output {
            Ok(o) if o.exit_code == 0 => String::from_utf8_lossy(&o.stdout).to_string(),
            Ok(o) => {
                debug!(
                    stderr = %String::from_utf8_lossy(&o.stderr),
                    "docker ps failed during reaper check"
                );
                return 0;
            }
            Err(e) => {
                debug!(error = %e, "docker not available for reaper");
                return 0;
            }
        };

        let now = chrono::Utc::now();
        let mut reaped = 0;

        for line in output.lines() {
            let parts: Vec<&str> = line.splitn(3, '\t').collect();
            if parts.len() < 3 {
                continue;
            }
            let container_id = parts[0];
            let created_at = parts[1];
            let container_name = parts[2];

            let age = match parse_docker_timestamp(created_at) {
                Some(created) => now.signed_duration_since(created),
                None => {
                    debug!(
                        container = container_name,
                        timestamp = created_at,
                        "Failed to parse container timestamp"
                    );
                    continue;
                }
            };

            if age.num_seconds() > max_age.as_secs() as i64 {
                warn!(
                    container = container_name,
                    age_secs = age.num_seconds(),
                    "Reaping orphaned container"
                );
                let _ = self
                    .cli
                    .run(vec![
                        "rm".to_string(),
                        "-f".to_string(),
                        container_id.to_string(),
                    ])
                    .await;
                reaped += 1;
            }
        }

        let reap_duration_ms = reap_start.elapsed().as_millis() as u64;
        if reaped > 0 {
            info!(
                reaped,
                duration_ms = reap_duration_ms,
                "Reaper cycle complete"
            );
        }

        reaped
    }

    /// Spawn a background task that periodically reaps orphaned containers.
    ///
    /// The task runs every `interval` and calls `reap_orphaned_containers(max_age)`.
    /// It stops cleanly when `shutdown` is cancelled.
    pub fn spawn_reaper(
        &self,
        max_age: std::time::Duration,
        interval: std::time::Duration,
        shutdown: tokio_util::sync::CancellationToken,
    ) -> tokio::task::JoinHandle<()> {
        let manager = self.clone();
        tokio::spawn(async move {
            let mut ticker = tokio::time::interval(interval);
            // Skip the first immediate tick (startup reap already ran)
            ticker.tick().await;

            loop {
                tokio::select! {
                    _ = ticker.tick() => {
                        let reaped = manager.reap_orphaned_containers(max_age).await;
                        if reaped > 0 {
                            info!("Periodic reaper cleaned up {} orphaned container(s)", reaped);
                        }
                    }
                    _ = shutdown.cancelled() => {
                        info!("Container reaper shutting down");
                        break;
                    }
                }
            }
        })
    }
}

/// Parse a Docker `CreatedAt` timestamp (e.g., "2024-01-15 10:30:00 -0700 MST").
///
/// Docker uses a non-standard format with both numeric offset and timezone abbreviation.
/// We parse the numeric offset portion and ignore the abbreviation.
pub fn parse_docker_timestamp(s: &str) -> Option<chrono::DateTime<chrono::Utc>> {
    // Docker format: "2024-01-15 10:30:00 -0700 MST"
    // We need: "2024-01-15 10:30:00 -0700" (drop the TZ abbreviation)
    let parts: Vec<&str> = s.splitn(4, ' ').collect();
    if parts.len() < 3 {
        return None;
    }
    let without_tz_name = format!("{} {} {}", parts[0], parts[1], parts[2]);
    chrono::DateTime::parse_from_str(&without_tz_name, "%Y-%m-%d %H:%M:%S %z")
        .ok()
        .map(|dt| dt.with_timezone(&chrono::Utc))
}
